# Generated by Django 3.0.3 on 2020-04-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yohack_app', '0006_auto_20200425_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
