# Generated by Django 3.0.3 on 2020-04-25 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yohack_app', '0007_questions_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentors',
            name='cases',
        ),
        migrations.AddField(
            model_name='mentors',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yohack_app.Case'),
        ),
    ]
