# Generated by Django 3.0.3 on 2020-04-25 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yohack_app', '0008_auto_20200425_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='cases',
        ),
        migrations.AddField(
            model_name='questions',
            name='cases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yohack_app.Case'),
        ),
    ]
